apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myhero-app
spec:
  hosts:
  - "app.10.10.20.208.xip.io"
  gateways:
  - myhero-gateway
  - mesh
  http:
  - route:
    - destination:
        host: myhero-app.myhero.svc.cluster.local
