apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myhero-app
spec:
  hosts:
  - "app.kubectl -n myhero apply -f 3-app_HTTP_abort.yml.xip.io"
  gateways:
  - myhero-gateway
  - mesh
  http:
  - fault:
      abort:
        percent: 100
        httpStatus: 500
    route:
    - destination:
        host: myhero-app.myhero.svc.cluster.local
